"""
Fill empty/fallback mock tool data for _data read-service tools.

Workflows generated before proper mock data generation (or where _generate_mock_tool_data
failed) end up with response_template = "No data found for {query} in {object_id}."
This script detects those tools, regenerates real JSON data for them via LLM, and
writes the patched samples back.  Affected test cases are then re-generated by the
pipeline (pass --pipeline to do this automatically).

Usage:
    python -m src.data.fill_mock_data \\
        --workflows outputs/data/zapier/ITER4/workflows.jsonl \\
        --model claude-sonnet-4-6 \\
        --workers 8

    # Also trigger pipeline to regenerate affected TCs:
    python -m src.data.fill_mock_data \\
        --workflows outputs/data/zapier/ITER4/workflows.jsonl \\
        --pipeline \\
        --templates data/zapier/raw/templates.yaml \\
        --target-dir outputs/data/zapier/ITER4
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from dotenv import load_dotenv
from tqdm import tqdm

load_dotenv()

from src.data.schema import Workflow
from src.data.llm import create_llm
from src.data.utils import infer_provider, add_common_args
from src.data.generate_workflows import _generate_mock_tool_data, _infer_data_hint


# ── Helpers ───────────────────────────────────────────────────────────────────

_FALLBACK_RE = re.compile(r"^No data found for", re.IGNORECASE)
_JSON_FIELD_RE = re.compile(r'"(\w+)"\s*:')


def _is_empty_tool(response_template: str) -> bool:
    """Return True if the template contains no JSON fields (fallback/placeholder)."""
    return not _JSON_FIELD_RE.search(response_template)


def _find_empty_data_tools(sample: Workflow) -> list[str]:
    """Return tool_names of _data tools with no real JSON data."""
    return [
        t.tool_name
        for t in sample.tools
        if "_data" in t.tool_name and _is_empty_tool(t.response_template)
    ]


def _fill_sample(llm, sample: Workflow) -> tuple[Workflow, int]:
    """Fill empty _data tools in-place. Returns (sample, num_filled)."""
    empty_tools = _find_empty_data_tools(sample)
    if not empty_tools:
        return sample, 0

    step_texts = [s.text for s in sample.steps if s.text]
    filled = 0

    for tool_name in empty_tools:
        # Find the owning object to get description
        owner = next(
            (o for o in sample.objects if tool_name in (o.skills or [])),
            None,
        )
        if owner is None:
            # Fall back to scanning behavior for the tool reference
            owner = next(
                (o for o in sample.objects if tool_name in (o.behavior or "")),
                None,
            )

        description = ""
        if owner:
            description = (owner.state_description or "").strip() or owner.role

        new_tool = _generate_mock_tool_data(llm, tool_name, description, step_texts)
        if new_tool is None:
            continue

        # Replace the existing tool in-place
        for i, t in enumerate(sample.tools):
            if t.tool_name == tool_name:
                # Preserve existing triggers (added by sequential_confirmation auto-patch)
                new_tool.triggers = t.triggers
                sample.tools[i] = new_tool
                filled += 1
                break

    return sample, filled


# ── I/O ───────────────────────────────────────────────────────────────────────

def _load_samples(path: Path) -> list[tuple[int, str, Workflow | None]]:
    """Load all lines; parse Workflow where possible. Returns (line_idx, raw_line, sample|None)."""
    result = []
    with open(path) as f:
        for i, line in enumerate(f):
            raw = line.rstrip("\n")
            if not raw.strip():
                result.append((i, raw, None))
                continue
            try:
                s = Workflow.model_validate(json.loads(raw))
                result.append((i, raw, s))
            except Exception:
                result.append((i, raw, None))
    return result


def _save_samples(path: Path, rows: list[tuple[int, str, Workflow | None]]) -> None:
    with open(path, "w") as f:
        for _, raw, sample in rows:
            if sample is not None:
                f.write(sample.model_dump_json() + "\n")
            else:
                f.write(raw + "\n")


# ── Main ──────────────────────────────────────────────────────────────────────

def fill(
    workflows_path: Path,
    model: str,
    provider: str,
    workers: int,
    dry_run: bool,
) -> set[str]:
    """Fill empty mock data tools. Returns set of patched sample IDs."""
    rows = _load_samples(workflows_path)
    samples_to_fix = [
        (i, s) for i, _, s in rows
        if s is not None and _find_empty_data_tools(s)
    ]

    total_empty = sum(len(_find_empty_data_tools(s)) for _, s in samples_to_fix)
    print(f"Workflows with empty _data tools: {len(samples_to_fix)} "
          f"({total_empty} tools to fill)")

    if not samples_to_fix:
        print("Nothing to do.")
        return set()

    if dry_run:
        for _, s in samples_to_fix:
            tools = _find_empty_data_tools(s)
            print(f"  {s.id}: {tools}")
        print("Dry run — no changes written.")
        return set()

    llm = create_llm(model=model, provider=provider)
    patched_ids: set[str] = set()
    row_map = {i: idx for idx, (i, _, s) in enumerate(rows) if s is not None}

    def _do_one(args: tuple[int, Workflow]) -> tuple[int, Workflow, int]:
        i, sample = args
        sample, n = _fill_sample(llm, sample)
        return i, sample, n

    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = {pool.submit(_do_one, item): item for item in samples_to_fix}
        for fut in tqdm(as_completed(futures), total=len(futures), desc="Filling mock data"):
            try:
                i, sample, n_filled = fut.result()
                if n_filled > 0:
                    # Update in rows
                    row_idx = row_map[i]
                    rows[row_idx] = (i, sample.model_dump_json(), sample)
                    patched_ids.add(sample.id)
                    print(f"  {sample.id}: filled {n_filled} tool(s)")
                else:
                    print(f"  {futures[fut][1].id}: 0 tools filled (LLM returned None for all)",
                          file=sys.stderr)
            except Exception as e:
                orig_sample = futures[fut][1]
                print(f"  WARN: {orig_sample.id} failed: {e}", file=sys.stderr)

    _save_samples(workflows_path, rows)
    print(f"\nPatched {len(patched_ids)} sample(s) → {workflows_path}")
    return patched_ids


# ── CLI ───────────────────────────────────────────────────────────────────────

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--workflows", required=True, type=Path,
                   help="Path to workflows.jsonl")
    p.add_argument("--model", default="claude-sonnet-4-6")
    p.add_argument("--provider", default=None)
    p.add_argument("--workers", type=int, default=4)
    p.add_argument("--dry-run", action="store_true",
                   help="Print what would change without writing")
    p.add_argument("--pipeline", action="store_true",
                   help="After filling, re-run the pipeline to regenerate affected TCs")
    p.add_argument("--templates", type=Path, default=Path("data/zapier/raw/templates.yaml"),
                   help="Templates YAML (required with --pipeline)")
    p.add_argument("--target-dir", type=Path, default=None,
                   help="Pipeline target dir (required with --pipeline)")
    p.add_argument("--pipeline-workers", type=int, default=8)
    return p


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    provider = args.provider or infer_provider(args.model)

    patched = fill(
        workflows_path=args.workflows,
        model=args.model,
        provider=provider,
        workers=args.workers,
        dry_run=args.dry_run,
    )

    if patched and args.pipeline:
        if not args.target_dir:
            print("ERROR: --target-dir required with --pipeline", file=sys.stderr)
            sys.exit(1)
        import subprocess
        id_flags = [f for sid in sorted(patched) for f in ("--id", sid)]
        cmd = [
            "python", "-m", "src.data.pipeline",
            "-i", str(args.templates),
            "--target-dir", str(args.target_dir),
            "--workers", str(args.pipeline_workers),
            *id_flags,
        ]
        print(f"\nRunning pipeline for {len(patched)} patched sample(s)…")
        print("  " + " ".join(cmd))
        subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
